<?php

namespace App\Home\Controllers;

use App\Common\Controllers\TopController;

class ControllerBase extends TopController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}